# Generated by Django 3.2 on 2024-12-17 05:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe', '0002_listitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikedRecipe',
            fields=[
                ('recipe_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('author_id', models.IntegerField()),
                ('author_name', models.CharField(max_length=255)),
                ('total_time', models.CharField(max_length=50)),
                ('date_published', models.DateField()),
                ('description', models.TextField()),
                ('images', models.URLField()),
                ('recipe_category', models.CharField(max_length=255)),
                ('keywords', models.TextField()),
                ('recipe_ingredient_parts', models.TextField()),
                ('calories', models.FloatField()),
                ('fat_content', models.FloatField()),
                ('saturated_fat_content', models.FloatField()),
                ('cholesterol_content', models.FloatField()),
                ('sodium_content', models.FloatField()),
                ('carbohydrate_content', models.FloatField()),
                ('fiber_content', models.FloatField()),
                ('sugar_content', models.FloatField()),
                ('protein_content', models.FloatField()),
                ('recipe_servings', models.IntegerField()),
                ('recipe_instructions', models.TextField()),
                ('recipe_ingredients', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_recipes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
