# Generated by Django 3.2 on 2024-12-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_likedrecipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likedrecipe',
            name='date_published',
            field=models.CharField(max_length=50),
        ),
    ]
