# Generated by Django 3.2 on 2024-12-18 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_alter_likedrecipe_date_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likedrecipe',
            name='date_published',
        ),
        migrations.RemoveField(
            model_name='likedrecipe',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='likedrecipe',
            name='recipe_category',
        ),
        migrations.RemoveField(
            model_name='likedrecipe',
            name='recipe_ingredient_parts',
        ),
        migrations.RemoveField(
            model_name='likedrecipe',
            name='recipe_servings',
        ),
    ]
