# Generated by Django 3.2 on 2025-01-16 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_auto_20241218_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='listitem',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='recipe.likedrecipe'),
        ),
    ]
