# Generated by Django 3.2 on 2025-01-16 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0008_listitem_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='listitem',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
